# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '计算器.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLineEdit, QPushButton, QSizePolicy,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(331, 520)
        self.lineEdit = QLineEdit(Form)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 10, 301, 141))
        self.pushButton_1 = QPushButton(Form)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setGeometry(QRect(10, 400, 61, 51))
        font = QFont()
        font.setPointSize(20)
        self.pushButton_1.setFont(font)
        self.pushButton_2 = QPushButton(Form)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(90, 400, 61, 51))
        self.pushButton_2.setFont(font)
        self.pushButton_3 = QPushButton(Form)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(170, 400, 61, 51))
        self.pushButton_3.setFont(font)
        self.pushButton_7 = QPushButton(Form)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(10, 280, 61, 51))
        self.pushButton_7.setFont(font)
        self.pushButton_8 = QPushButton(Form)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(90, 280, 61, 51))
        self.pushButton_8.setFont(font)
        self.pushButton_6 = QPushButton(Form)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(170, 340, 61, 51))
        self.pushButton_6.setFont(font)
        self.pushButton_5 = QPushButton(Form)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(90, 340, 61, 51))
        self.pushButton_5.setFont(font)
        self.pushButton_4 = QPushButton(Form)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(10, 340, 61, 51))
        self.pushButton_4.setFont(font)
        self.pushButton_9 = QPushButton(Form)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(170, 280, 61, 51))
        self.pushButton_9.setFont(font)
        self.pushButton_0 = QPushButton(Form)
        self.pushButton_0.setObjectName(u"pushButton_0")
        self.pushButton_0.setGeometry(QRect(90, 460, 61, 51))
        self.pushButton_0.setFont(font)
        self.pushButton_percent = QPushButton(Form)
        self.pushButton_percent.setObjectName(u"pushButton_percent")
        self.pushButton_percent.setGeometry(QRect(10, 460, 61, 51))
        font1 = QFont()
        font1.setPointSize(18)
        self.pushButton_percent.setFont(font1)
        self.pushButton_dot = QPushButton(Form)
        self.pushButton_dot.setObjectName(u"pushButton_dot")
        self.pushButton_dot.setGeometry(QRect(170, 460, 61, 51))
        self.pushButton_dot.setFont(font)
        self.pushButton_init = QPushButton(Form)
        self.pushButton_init.setObjectName(u"pushButton_init")
        self.pushButton_init.setGeometry(QRect(10, 220, 61, 51))
        font2 = QFont()
        font2.setPointSize(14)
        self.pushButton_init.setFont(font2)
        self.pushButton_back = QPushButton(Form)
        self.pushButton_back.setObjectName(u"pushButton_back")
        self.pushButton_back.setGeometry(QRect(250, 220, 61, 51))
        self.pushButton_mul = QPushButton(Form)
        self.pushButton_mul.setObjectName(u"pushButton_mul")
        self.pushButton_mul.setGeometry(QRect(170, 220, 61, 51))
        self.pushButton_mul.setFont(font1)
        self.pushButton_div = QPushButton(Form)
        self.pushButton_div.setObjectName(u"pushButton_div")
        self.pushButton_div.setGeometry(QRect(90, 220, 61, 51))
        self.pushButton_div.setFont(font1)
        self.pushButton_dec = QPushButton(Form)
        self.pushButton_dec.setObjectName(u"pushButton_dec")
        self.pushButton_dec.setGeometry(QRect(250, 280, 61, 51))
        self.pushButton_dec.setFont(font1)
        self.pushButton_add = QPushButton(Form)
        self.pushButton_add.setObjectName(u"pushButton_add")
        self.pushButton_add.setGeometry(QRect(250, 340, 61, 51))
        self.pushButton_add.setFont(font1)
        self.pushButton_equal = QPushButton(Form)
        self.pushButton_equal.setObjectName(u"pushButton_equal")
        self.pushButton_equal.setGeometry(QRect(250, 400, 61, 111))
        self.pushButton_equal.setFont(font)
        self.pushButton_14 = QPushButton(Form)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(10, 160, 61, 51))
        self.pushButton_14.setFont(font2)
        self.pushButton_21 = QPushButton(Form)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(90, 160, 61, 51))
        self.pushButton_21.setFont(font2)
        self.pushButton_23 = QPushButton(Form)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(250, 160, 61, 51))
        self.pushButton_23.setFont(font2)
        self.pushButton_24 = QPushButton(Form)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(170, 160, 61, 51))
        self.pushButton_24.setFont(font2)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"\u8ba1\u7b97\u5668", None))
        self.pushButton_1.setText(QCoreApplication.translate("Form", u"1", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"2", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"3", None))
        self.pushButton_7.setText(QCoreApplication.translate("Form", u"7", None))
        self.pushButton_8.setText(QCoreApplication.translate("Form", u"8", None))
        self.pushButton_6.setText(QCoreApplication.translate("Form", u"6", None))
        self.pushButton_5.setText(QCoreApplication.translate("Form", u"5", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"4", None))
        self.pushButton_9.setText(QCoreApplication.translate("Form", u"9", None))
        self.pushButton_0.setText(QCoreApplication.translate("Form", u"0", None))
        self.pushButton_percent.setText(QCoreApplication.translate("Form", u"%", None))
        self.pushButton_dot.setText(QCoreApplication.translate("Form", u".", None))
        self.pushButton_init.setText(QCoreApplication.translate("Form", u"C", None))
        self.pushButton_back.setText(QCoreApplication.translate("Form", u"\u56de\u9000", None))
        self.pushButton_mul.setText(QCoreApplication.translate("Form", u"\u00d7", None))
        self.pushButton_div.setText(QCoreApplication.translate("Form", u"\u00f7", None))
        self.pushButton_dec.setText(QCoreApplication.translate("Form", u"-", None))
        self.pushButton_add.setText(QCoreApplication.translate("Form", u"+", None))
        self.pushButton_equal.setText(QCoreApplication.translate("Form", u"=", None))
        self.pushButton_14.setText(QCoreApplication.translate("Form", u"MC", None))
        self.pushButton_21.setText(QCoreApplication.translate("Form", u"M+", None))
        self.pushButton_23.setText(QCoreApplication.translate("Form", u"ME", None))
        self.pushButton_24.setText(QCoreApplication.translate("Form", u"M-", None))
    # retranslateUi

